# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main

jobs:
  test:
    name: Test on JSK ${{ matrix.jdk_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk_version:
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.jdk_version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk_version }}
    - name: Test with Maven
      run: mvn -B test --file pom.xml
